### ISSUE TITLE
Syntax Error in M6WebStatsdExtension.php

### ISSUE THREAD

**Issue by angezanetti** [M6Web/StatsdBundle#35]
Hey guys, 

I just installed and try to use your StatsBundle in my Symfony app. 
My configuration is quite basic for now:

`config.yml`:
```     
m6_statsd:
      servers:
        default:
            address: 'udp://192.168.101.154'
            port:     8125
     clients:
         default:
            servers:   ["default"]
 ```

In my controller i added a `$this->get('m6_statsd')->increment('toto');`

Then i tried to use that controller but it returns a syntax error:
`FatalErrorException in M6WebStatsdExtension.php line 26: Parse Error: syntax error, unexpected '['`

I'm running PHP 5.3, it seems that the short array syntax is not supported before the 5.4 version...

**Comment by mikaelrandy** [comment]
Hello @angezanetti,

How have you installed this bundle on a PHP 5.3 instance ?
The composer.json require PHP 5.4+ (https://github.com/M6Web/StatsdBundle/blob/master/composer.json#L19)

**Comment by angezanetti** [comment]
Oh i didn't saw the composer restrictions, i generated the vendors on another machine. 
Is there any reason for this limitation? 

Well, don't bother you about this, i'm gotta try the liuggio

**Comment by mikaelrandy** [comment]
Yep, there is a reason : the syntax used ;)

Sorry for you :'(

**Comment by mikaelrandy** [comment]
To be more explicit : PHP 5.3 reach its End Of Life date on august 14, 2014, so we dont want to maintain our apps on this version.

Please see http://php.net/supported-versions.php
