### ISSUE TITLE
creation systématique du propertyAccessor fait perdre du temps

### ISSUE THREAD

**Issue by omansour** [M6Web/StatsdBundle#41]
https://github.com/M6Web/StatsdBundle/blob/master/src/Client/Client.php#L153

On devrait créer propertyAccessor lors de la construction de l'objet ?

**Comment by cedvan** [comment]
:+1:

**Comment by mguillermin** [comment]
en effet, ça semble mieux :+1:

**Comment by omansour** [comment]
$propertyAccessor->getValue est très consommateur. A voir si on peut faire un truc plus simple sur avec la reflexion ou autre ?

**Comment by t-geindre** [comment]
On devrait même instancier le `PropertyAccessor` _on demand_.

**Comment by omansour** [comment]
@t-geindre que veux tu dire par là ?
