### ISSUE TITLE
2.12.1 bug

### ISSUE THREAD

**Issue by jdeniau** [M6Web/StatsdBundle#43]
Since the 2.12.1 version, I got a 
``` [Symfony\Component\DependencyInjection\Exception\RuntimeException]             
  Unable to dump a service container if a parameter is an object or a resource.                                                                             
```
error.

I think it is because of [this](https://github.com/M6Web/StatsdBundle/blob/144862246094885655452c8cffddecd6b4f48891/src/DependencyInjection/M6WebStatsdExtension.php#L164)

You should probably not call the method itself but use the dependency injection system to call it (via a factory probably).: 
```
PropertyAccess\PropertyAccess::createPropertyAccessorBuilder()->enableMagicCall()->getPropertyAccessor()
```

**Comment by omansour** [comment]
ho shit ! 

unit tests arent showing this. Any idea to solve this @jdeniau ?

**Comment by jdeniau** [comment]
I think something like this:
```::php
$definition = new Definition('Symfony\Component\PropertyAccess\PropertyAccessorBuilder');
$definition->setFactory(['PropertyAccess\PropertyAccess', 'createPropertyAccessorBuilder']);
$definition->addMethodCall('enableMagicCall');
$definition->addMethodCall('getPropertyAccessor');
```

But I'm really not sure for the last 2 lines: you may be have to chain the factory process, which is not easy to understand.

Another way is to create a custom Factory like this:
```::php
class PropertyAccessorFactory {
    public static function createPropertyAccessor()
    {
        return PropertyAccess\PropertyAccess::createPropertyAccessorBuilder()->enableMagicCall()->getPropertyAccessor();
    }
}
```

and in your DependencyInjection:
```
$paDefinition = new Definition('Symfony\Component\PropertyAccess\PropertyAccessorBuilder');
$paDefinition->setFactory(['M6Web\Foo\Bar\PropertyAccessorFactory', 'createPropertyAccessor']);

$definition->addMethodCall('setPropertyAccessor', $paDefinition);
```

**Comment by mguillermin** [comment]
@omansour You could also simply use a kind of "lazy-initialization" of the `PropertyAccessor` directly in the `Client` class (IMO there is no need to use the container here): 

```php
class Client
{
    //...
    protected $propertyAccessor = null;
    //...
    private function getPropertyAccessor()
    {
        if (is_null($this->propertyAccessor)) {
            $this->propertyAccessor = PropertyAccess::createPropertyAccessorBuilder()
                ->enableMagicCall()
                ->getPropertyAccessor();
        }

        return $this->propertyAccessor;
    }
    //...
    private function replaceInNodeFormMethod($event, $eventName, $node)
    {
        $propertyAccessor = $this->getPropertyAccessor();
        //...
    }
    //...
}
```

**Comment by omansour** [comment]
@mguillermin I think i prefer this way https://github.com/M6Web/StatsdBundle/pull/44/files because it doesn't involve the createPropertyAccessorBuilder. 

the factory in the middle of the get sounds too magical for me.

**Comment by omansour** [comment]
PR https://github.com/M6Web/StatsdBundle/pull/44 should fix this issue. I will rebuild the 2.12.1 version

**Comment by omansour** [comment]
actually I well release 2.12.2 instead
