### ISSUE TITLE
Pouvoir injecter un prefix aux noms de metrique par service

### ISSUE THREAD

**Issue by ChoOo7** [M6Web/StatsdBundle#50]
Bonjour

Il pourrait être chouette de pouvoir injecter par un service un nom de métrique qui préfixerait toutes les métriques envoyées.

Mon cas d'usage en particulier pour mieux comprendre.

Je développe une API REST, je souhaite remonter des informations à mon statsd. Jusque là tout va bien ! 

Mon application se connecte à différentes bases de données / clients en fonction de paramètres de ma requête (en fonction d'un param GET apiKey). Je souhaite que mes métriques aient toute la forme

eztvservices.<apiKeyFromRequest>.<leNomDeMaMetriqueIndiquéDansMonApplicatif>

Néanmoins, je ne souhaite jamais, dans mon application, avoir à indiquer "eztvservices.<apiKeyFromRequest>", cela serait injecté par mon service.

J'ai actuellement réalisé cette fonctionnalité en utilisant mon propre service, lequel a dans son constructeur le service Request & statsd. Cela fonctionne. Mais cela devient plus compliqué lorsque je souhaite binder des événements.

Genre
m6_statsd:
    clients:
        default:
            events:
                forum.read:
                    increment : mysite.forum.<name>.read

Merci !

**Comment by omansour** [comment]
pour répondre à ce besoin, à mon avis, il faut utiliser la fonction de bindings sur des events https://github.com/M6Web/StatsdBundle/blob/master/doc/usage.md#bind-on-events et faire en sorte que ton event ait une méthode pour renvoyer l'info que tu veux depuis la conf de sf2.
