### ISSUE TITLE
Utiliser le console.terminate event pour flusher les metriques

### ISSUE THREAD

**Issue by johndodev** [M6Web/StatsdBundle#51]
Hello,

de la même manière que dans une request normale, où les métriques sont envoyé dans un listener de kernel.terminate par défaut, est-ce qu'il ne serait pas judicieux de faire la même chose pour les commandes ?

Je l'ai fait dans ma branche InfluxDb qu'on utilise en prod, ça se traduit simplement par envoyer les clients dans le consoleListener et de rajouter un tag *kernel.event_listener* vers une fonction qui appel le send() des clients (avec une priority négative genre -255).
J'ai pas encore pushé dans la PR en cours, c'est peut-être à dissocier si ça vous intéresse ?

Par contre si on le fait ça soulève quelques questions : 
- Est-ce qu'on le fait que dans le cas ou *console_events: true* ou tous le temps (vu qu'on veut peut-être juste des events de console persos sans la surcharge du bundle) ?
- Dans ce cas est-ce que l'option "immediate_send" est encore utile ?

Edit : à voir dans ce commit : https://github.com/johndodev/StatsdBundle/commit/4ac0e276f3408cbb70e16ea6908517362ac2026c

**Comment by omansour** [comment]
Salut, selon moi ce besoin est adressé par https://github.com/M6Web/StatsdBundle/blob/master/doc/usage.md#console-custom-events

non ?

**Comment by johndodev** [comment]
Non pas exactement, là ça active les événements de la console, mais il faut du coup mettre un *immediate_send* dans la config sinon aucun des événements ne sera envoyé (d'ailleurs du coup je suis pas sûr que l'exemple de la doc fonctionne). Et avec un immediate_send à true ce qui est un peu dommage c'est que si on balance 500 events (ou métriques) dans une commande, ça va envoyer 500 requêtes à statsd.

**Comment by omansour** [comment]
le binding d'event n'envoi rien à statsd. Pour envoyer à statsd il faut le kernel terminate ou un immediate_sent sur un event. 

donc si tu fait 

```json 
m6web.console.terminate:
                    immediate_send: true
```

ça n'envoi à statsd qu'une fois par commande

**Comment by johndodev** [comment]
Ha oui se brancher sur cet event sans rien binder et juste pour le send ne m'était pas venu à l'idée en effet. 

Après je trouve que c'est un moyen un peu détourné et pas très naturel d'adresser le besoin, pour plusieurs raisons.
 - il n'y a pas besoin de le faire pour une requête http (pas en console), puisque c'est déjà fait dans le lister du kernel terminate.
- ca revient à appeler une fonction qui s’appelle "handleEvent" juste pour flusher dans statsd en fait, bon on a rien vu.
- avec la doc j'avais compris qu'il fallait faire un truc du genre 

```yml
mon.event.console:
  increment: node
  immediate_send: true
```
d'ou le soucis.

Une des possibilité serait d'insérer ce bout de config implicitement dans la config via  statsdExtension.php pour reproduire le comportement classique sans que l'utilisateur ai besoin de l'expliciter dans la config. Parce que s'il le fait pas (genre il se dit "non je veux faire comme dans mon code normal, on envoie à la fin), il va naturellement ne pas mettre le immediate_send: true, sauf que du coup ses événements ne vont jamais s'envoyer, ce qui est incohérent.

C'est juste cette différence de comportement entre le code "normal" et les commandes qui me gène, je trouve que ça complexifie l'utilisation, ou alors faudrait juste mettre ce trick dans la doc ?
