### ISSUE TITLE
Symfony 5 compatibility

### ISSUE THREAD

**Issue by simonberger** [M6Web/StatsdBundle#74]
I noticed there is no Symfony 5 compatibility yet.
Someone seemed to already tackle this in a fork. https://github.com/birkof/StatsdBundle

**Comment by Oliboy50** [comment]
it seems that we already have these PRs for symfony 5 compat: 
- https://github.com/M6Web/StatsdBundle/pull/72
- https://github.com/M6Web/StatsdBundle/pull/70
- https://github.com/M6Web/StatsdBundle/pull/69

**Comment by simonberger** [comment]
True, if those Deprecations have been fixed it is maybe not much more than changing the composer.json.

**Comment by simonberger** [comment]
Fixed in #75
